Translate x.parse
aspnet/EntityFrameworkCore pull request #28337
Opened 2022-06-28 18:38 UTC by MaRK0960

Fixes #28287

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

2022-06-28 18:47 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
> +                new SqlServerParseTranslator(sqlExpressionFactory),
alphabetical order

2022-06-28 18:48 UTC, MaRK0960 commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> +        // Cosmos client evaluation. Issue #17246.
Are these comments in the right place?
They are in the `Convert.To` Methods.

2022-06-29 18:59 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerParseTranslator.cs
> +    private static readonly Dictionary<Type, string> TypeMapping = new()
ClrTypeToStoreTypeMap

2022-06-29 19:00 UTC, smitpatel commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> +        // Cosmos client evaluation. Issue #17246.
Yes. Can leave these as is.

2022-06-29 19:01 UTC, smitpatel commented
Can we also get tests which converts from actual string values. Also some negative tests where the string is not exactly parse-able and we verify database behavior.

2022-07-09 08:17 UTC, roji requested changes
Thanks for the changes. This looks almost ready, see below for some nits and test cleanup.

2022-07-09 08:17 UTC, roji commented on test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
> +            ss => ss.Set<Order>().Where(o => o.CustomerID == "ALFKI")
Merge the two Where clauses (here and below). Also consider removing the check for CustomerID - is there any reason to restrict to those rows only?

2022-07-09 08:17 UTC, roji commented on test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
> +        await AssertQuery(
Any reason for the 2nd test query? I can see this below as well - the point here generally isn't to check that the database operation works (we don't test the database, only EF), so I'm not sure what this one checks beyond the above.

Unless the extra queries add coverage for EF specifically, I think it's better to just do one query per test.

2022-07-09 08:17 UTC, roji commented on test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
> +    public virtual Task Short_Parse_Decimal_Bad_Format(bool async)
Is there a decimal here? Also, not sure what additional coverage this adds (same for others).

2022-07-11 11:08 UTC, MaRK0960 commented on test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
> +            ss => ss.Set<Order>().Where(o => o.CustomerID == "ALFKI")
Some rows are not parse-able, making them not suitable for this test.

2022-08-03 19:47 UTC, MaRK0960 commented
@roji Is there anything else?

2022-11-17 03:07 UTC, tmricardo7 commented
any updates on this @roji ?

2022-11-17 08:44 UTC, roji commented
@MaRK0960 sorry for not giving this any attention - the 7.0 release (and resulting bugfixes) are have taken up most of my time. I'll do my best to look at this again in the next couple of weeks.

2023-04-24 17:36 UTC, roji requested changes, later dismissed
@MaRK0960 apologies for letting this sit for so long without reviewing. Aside from one important note (the one about type inference), I think this is more or less ready; I'm happy to also take over this (as we haven't responded for so long), let me know what you want to do.

2023-04-25 12:22 UTC, MaRK0960 commented
No problem, I will continue working on it.

2023-04-25 14:40 UTC, roji commented
@MaRK0960 ok great, let me know if you run out of time or something, otherwise you can ask for another review after you've made changes etc.

2023-04-27 20:32 UTC, MaRK0960 commented on test/EFCore.InMemory.FunctionalTests/Query/NorthwindFunctionsQueryInMemoryTest.cs
> +    public override Task Byte_Parse_Non_Numeric_Bad_Format(bool async)
There is a test in SqlServer that checks if all tests are overridden:

https://github.com/dotnet/efcore/blob/3f10651197075a206fff070e408efb60e835228d/test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs#L26-L28

And if the assertion is done in the base class, we can't override it.

2023-05-26 07:56 UTC, Saibamen commented
@roji: ping

2025-01-06 21:02 UTC, MaRK0960 commented
I refactored the tests to their new suites, and removed the error tests because they seemed irrelevant to testing EF.
Is there anything else?

2026-06-09 16:58 UTC, AndriySvyryd commented
@MaRK0960 Sorry for the delay. I am taking over for @roji. Please rebase on latest main

2026-07-10 19:45 UTC, AndriySvyryd approved these changes
Thanks for your contribution!

2026-07-10 20:43 UTC, merged