Optimize null propagation
aspnet/EntityFrameworkCore pull request #34127
Opened 2024-06-30 19:42 UTC by ranma42

When a CASE expression simply replicates SQL null propagation, simplify it.

Contributes to #34126.

2024-07-01 11:50 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +                return null; // true
maybe it would be cleaner to return a `TRUE` expression here.

2024-07-02 23:06 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +                return null; // true
With #34133 merged, it definitely is 🚀

2024-07-12 12:30 UTC, roji requested changes, later dismissed
Great work as always @ranma42, it's really nice to see our SQL baselines getting progressively tighter and better.

See mainly nits below.

2024-07-12 12:30 UTC, roji commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +            else if (expression is SqlFunctionExpression { IsNullable: true } func)
Interestingly, if the node isn't nullable, then the checks can also be elided - though that elision sould take place elsewhere. This makes me think that we can introduce some basic simplifications in SqlExpressionFactory.IsNull/IsNotNull, recognizing the basic non-nullable node types...

2024-07-12 13:08 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +                && binary.OperatorType is not (ExpressionType.AndAlso or ExpressionType.OrElse))
`AndAlso(FALSE, NULL)` is `FALSE`
`OrElse(TRUE, NULL)` is `TRUE`

2024-07-12 13:11 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +            else if (expression is SqlFunctionExpression { IsNullable: true } func)
those are already removed in `ProcessNullNotNull`

2024-07-12 13:13 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +            if (expression is SqlUnaryExpression unary
will it work even if the result is `void`? I am unable to get its syntax right :\

2024-07-12 13:13 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +            else if (expression is SqlFunctionExpression { IsNullable: true } func)
this function is mostly based on `ProcessNullNotNull` (which, just like this function, ignores `AtTimeZone`, `Collate`, ...)

2024-07-12 13:16 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +                && unary.OperatorType is ExpressionType.Not or ExpressionType.Negate or ExpressionType.Convert)
the advantage of specifying them in a positive way is that changing the supported `OperatorType`s is safe
OTOH it is unlikely to happen and would likely require other changes across the repo, so I can replace this by exclusing `Equal` and `NotEqual` if that is easier to read

2024-07-12 13:25 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +        // FIXME: unify nullability computations
This is what I was considering doing in https://github.com/dotnet/efcore/issues/33889#issuecomment-2208732463 (instead of simple boolean nullability, propagate the "nullability expression") 😉 
I will most likely do that in a later experiment, at the very least to evaluate whether the nullability expressions are simple to create/consume.

2024-07-12 14:00 UTC, roji commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +        // FIXME: unify nullability computations
Yep, makes sense!

2024-07-12 14:01 UTC, roji commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +            else if (expression is SqlFunctionExpression { IsNullable: true } func)
I see... We should probablt fix that in both places - if you prefer not to do this in this PR we can open a separate issue.

2024-07-12 14:02 UTC, roji commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +                && binary.OperatorType is not (ExpressionType.AndAlso or ExpressionType.OrElse))
You're right, got my 3-value logic wrong there for a moment

2024-07-12 14:04 UTC, roji commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +                && unary.OperatorType is ExpressionType.Not or ExpressionType.Negate or ExpressionType.Convert)
Just noting that binary just below is negative rather than positive. Up to you - the possible values here in ExpressionType is a closed set, so it should be safe either way.

2024-07-12 16:38 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +            }
oops, this was swapped `(clause.Result, clause.Test)` vs `(clause.Test, clause.Result)`

2024-07-21 12:01 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +            else if (expression is SqlFunctionExpression { IsNullable: true } func)
I will add the part specific to this PR here; I added the other part in #34263

2024-07-27 10:58 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +            else if (expression is SqlFunctionExpression { IsNullable: true } func)
added in https://github.com/dotnet/efcore/pull/34127/commits/12a532b65a25804eb163fce2054952846f366b06

2026-06-09 16:36 UTC, AndriySvyryd commented
@ranma42 Could you rebase on latest main?

2026-06-13 19:54 UTC, ranma42 commented
> @ranma42 Could you rebase on latest main?

Sorry for the delay, I did not have much bandwidth to spare during the week.
It should now be rebased (with baselines updated and Copilot suggestions applied).

2026-06-14 07:20 UTC, ranma42 commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +                    break;
Good catch! Fixed. The operators that pass `IsValidOperator` are:
```
            case ExpressionType.Add:
            case ExpressionType.Subtract:
            case ExpressionType.Multiply:
            case ExpressionType.Divide:
            case ExpressionType.Modulo:
            case ExpressionType.And:
            case ExpressionType.AndAlso:
            case ExpressionType.Or:
            case ExpressionType.OrElse:
            case ExpressionType.LessThan:
            case ExpressionType.LessThanOrEqual:
            case ExpressionType.GreaterThan:
            case ExpressionType.GreaterThanOrEqual:
            case ExpressionType.Equal:
            case ExpressionType.NotEqual:
            case ExpressionType.Coalesce:
            case ExpressionType.ExclusiveOr:
```
Arithmetic operators (+,-,*,/,%), bitwise operators (&,|,^) and comparison operators (==,!=,<,<=,>,>=) all propagate null, hence I believe handling the 3 remaining ones (&&,||,??) should be ok.

2026-06-15 21:15 UTC, AndriySvyryd approved these changes
Thanks for your contribution!

2026-06-15 21:17 UTC, merged